name: Update README progress

on:
  push:
    branches:
      - master
jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Count folders
        run: | 
          EASY=$(ls -1 easy | wc -l)
          # MEDIUM=$(ls -1 medium | wc -l)
          # HARD=$(ls -1 hard | wc -l)
          if [ -f readme.md ]; then
            echo "OK - readme.md found"
          else
            echo "Error - readme.md does not exist"
          fi
          echo "Easy: $EASY"
          echo "Medium: $MEDIUM"
          echo "Hard: $HARD"

          # Update readme.md
          echo "showing folders"
          ls
          sed -i -E "s/(^\| Easy\s*\|\s*)[0-9]+(\s*\|.*$)/\1$EASY\2/" readme.md
          # sed -i "s/Medium: [0-9]*/Medium $MEDIUM/" readme.md
          # sed -i "s/Hard: [0-9]*/Hard $HARD/" readme.md

      - name: Commit changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add readme.md
          git commit -m "Update README with current progress"
          git push