name: Update README progress
on:
  push:
    branches:
      - master
jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Count folders
        run: | 
          # If directories dont exist, set count to 0
          if [ -d "easy" ]; then EASY=$(ls -1 easy | wc -l); else EASY=0; fi
          if [ -d "medium" ]; then MEDIUM=$(ls -1 medium | wc -l); else MEDIUM=0; fi
          if [ -d "hard" ]; then HARD=$(ls -1 hard | wc -l); else HARD=0; fi

          echo "Problems Solved: Easy ($EASY), Medium ($MEDIUM), Hard ($HARD)"          

          # Update readme.md
          sed -i -E "s/(^\| Easy\s*\|\s*)[0-9]+(\s*\|.*$)/\1$EASY\2/" readme.md
          sed -i -E "s/(^\| Medium\s*\|\s*)[0-9]+(\s*\|.*$)/\1$MEDIUM\2/" readme.md
          sed -i -E "s/(^\| Hard\s*\|\s*)[0-9]+(\s*\|.*$)/\1$HARD\2/" readme.md

          # Update progress bar
          sed -i -E "/^\| Easy/s#(https://geps.dev/progress/)[0-9]+#\1$EASY#" readme.md
          sed -i -E "/^\| Medium/s#(https://geps.dev/progress/)[0-9]+#\1$MEDIUM#" readme.md
          sed -i -E "/^\| Hard/s#(https://geps.dev/progress/)[0-9]+#\1$HARD#" readme.md

      - name: Commit changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add readme.md
          git commit -m "Update README with current progress"
          git push